package com.glory.spotflow_wallet.domain.transaction;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "transactions")
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "user_id", nullable = false)
    private Long userId;

    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false)
    private TransactionType type;

    /**
     * OUR idempotency key. Generated by us, sent to Spotflow, and matched back
     * against the `reference` field in webhook payloads.
     */
    @Column(name = "reference", nullable = false, unique = true)
    private String reference;

    /**
     * Spotflow's own ID for the transaction once known (spotflowReference / spotflow_reference).
     */
    @Column(name = "spotflow_reference")
    private String spotflowReference;

    @Column(name = "amount", nullable = false)
    private BigDecimal amount;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private TransactionStatus status;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    protected Transaction() {
        // for JPA
    }

    public static Transaction createPending(Long userId, TransactionType type, String reference, BigDecimal amount) {
        Transaction tx = new Transaction();
        tx.userId = userId;
        tx.type = type;
        tx.reference = reference;
        tx.amount = amount;
        tx.status = TransactionStatus.PENDING;
        tx.createdAt = LocalDateTime.now();
        tx.updatedAt = LocalDateTime.now();
        return tx;
    }

    public void markSuccess(String spotflowReference) {
        this.spotflowReference = spotflowReference;
        this.status = TransactionStatus.SUCCESS;
        this.updatedAt = LocalDateTime.now();
    }

    public void markFailed(String spotflowReference) {
        this.spotflowReference = spotflowReference;
        this.status = TransactionStatus.FAILED;
        this.updatedAt = LocalDateTime.now();
    }

    public void markAbandoned() {
        this.status = TransactionStatus.ABANDONED;
        this.updatedAt = LocalDateTime.now();
    }

    public Long getId() {
        return id;
    }

    public Long getUserId() {
        return userId;
    }

    public TransactionType getType() {
        return type;
    }

    public String getReference() {
        return reference;
    }

    public String getSpotflowReference() {
        return spotflowReference;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public TransactionStatus getStatus() {
        return status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }
}
